### ISSUE TITLE
Translation of the counter shows duplicate "subscribers" text

### ISSUE THREAD

**Issue by kaithililou** [mattyhempstead/yt-comment-sub-count#4]
As described in the title, the text following the count shows "X abonnés subscribers" (where X is the counter) when it only should show  "subscribers" or "abonnés" if the addon manages translations.
I'm on Firefox latest version, and it's in french that's why it shows "abonnés".
It's a little nitpick, but would be grateful if you could fix this.
Great addon by the way.
Thanks in advance.
![image](https://github.com/mattyhempstead/yt-comment-sub-count/assets/90206850/41f7ed94-0ada-4d56-a3d6-1af9cc69a9b3)

**Comment by MarioLiebisch** [comment]
This should be fixed with the changes from version 1.1.10 and now only read "4 abonnés" or `1 abonné". Only tested that in Chrome, though.
